### ISSUE TITLE
フォームの期日を一度変更した後もう一度当日に戻して確定すると作成日より前日の日付が登録されてしまう

### ISSUE THREAD

**Issue by kitutune** [kitutune/todo_app#37]

**Comment by gel1123** [comment]
`フォームの期日を一度変更した後もう一度当日に戻して確定すると` という前提条件は合ってますか？

午前7:50にTodoアプリを操作すると、表題の操作なしで、いきなりデフォルトの当日の日付のまま登録した場合にも、一日前の作成日に動くように見えます。

この挙動から推測される最もシンプルな原因は、

* バックエンドとフロントエンドでタイムゾーンが不一致になってる

ということですが、この点を含めて日時に関するオブジェクトの取り扱いにフロントエンド・バックエンドで問題はありませんか？

**Comment by kitutune** [comment]
原因
BEとFEでの取得している値違い（String⇨Dateへ変換の際にずれている）

**Comment by kitutune** [comment]
FEからBEにはDate型で渡していた
↓
FEからBEにStringで渡すに修正

上記に伴い型も変更
